name:
  main

on:
  push

jobs:
  RunBenchmarks:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: EndBug/add-and-commit@v9
       with:
         message: "Update benchmark"
     - run: echo "Hello world!" > hi.txt

