name:
  main

on:
  push

jobs:
  RunBenchmarks:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3

     - name: "Run benchmark"
       run: dotnet run -c release

     - name: Update benchmarks
       run: |
        chmod +x update.sh
        ./update.sh