name:
  main

on:
  push

jobs:
  RunBenchmarks:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3

     - name: "Run benchmark"
       run: echo "Hello world!" > hi.txt

     - name: Update benchmarks
       run: git add .
       run: git origin push